main: de.noneless.Main
version: 3.1
api-version: '1.20'
name: NonelessLobby

# Paper-spezifische Konfiguration
website: noneless.de
authors: [NonelessTeam]
description: Ein Lobby-System für NonelessMC
load: STARTUP

softdepend:
  - Essentials

commands:
  webRegister:
     description: Webseiten-Registrierung
  connect: 
     description: Verbinden zum SQL Server
  disconnect:
     description: Verbindung vom SQL Server trennen
  setlobby:
     description: Setze die Lobby
  spawn:
     description: Gehe zum Spawn
     aliases: [lobby, Area]
  addFriend:
     description: Füge Freunde hinzu
  delFriend:
     description: Entferne einen Freund
  vote:
     description: Bekomme den Vote-Link
  addItem:
     description: Füge ein Item zur Liste hinzu
  itemList:
     description: Zeige die Item-Liste
  report:
     description: Melde einen Spieler
  addGame:
     description: Füge Minigames/Arenen hinzu
  setRang:
     description: Setze den Rang eines Spielers
  removeKIcommand:
     description: Lösche KI-Kommando
  Magic:
     description: Aktiviere den Easymode
  addVIP:
     description: VIP-Verwaltung
  hilfe:
     description: Zeigt die Admin-Onlinezeiten