main: Main.Main
version: 3.0
api-version: 1.13
name: NonelessLobby

commands:
  webRegister:
     description: ???
  connect: 
     description: Verbinden zum SQL Server
  disconnect:
     description: Verbindung vom SQL Server trennen
  setlobby:
     description: Setze die lobby
  spawn:
     description: Gehe zum Spawn
     aliases: [lobby, Area]
  addFriend:
     description: Adde freunde!!!
  delFriend:
     description: Entfernt den angegebenen Freund
  vote:
     description: Bekomme den Vote Link
  addItem:
     description: Adde das Item zur Liste
  itemList:
     description: Siehe die Item Liste
  report:
     description: Reporte Einen Spieler
  addGame:
     description: Fügt Minigames/Arenen iein
  setRang:
     description: Setzt den Rang eines Spielers
  removeKIcommand:
     description: Loecht KiCommand
  Magic:
     description: Gibt dir die Macht des Easymode
  addVIP:
     description: Nicht fue Minecraft