main: Main.Main
version: 2.0
name: NonelessLobby

commands:
  setlobby:
     description: Setze die lobby
  spawn:
     description: Gehe zum Spawn
  addFriend:
     description: Adde freunde!!!
  delFriend:
     description: Entfernt den angegebenen Freund
  vote:
     description: Bekomme den Vote Link
  addItem:
     description: Adde das Item zur Liste
  itemList:
     description: Siehe die Item Liste
  report:
     description: Reporte Einen Spieler
  addGame:
     description: Fügt Minigames/Arenen in die liste
  setRang:
     description: Setzt den Rang eines Spielers
  removeKIcommand:
     description: Löscht KiCommand
  Magic:
     description: Gibt dir die Macht des Easymode
  addVIP:
     description: Nicht für Minecraft
  databaseconnect:
     description: Connected die DatenBank
  databasedisconnect:
     description: Connected die DatenBank