main: Main.Main
version: 2.0
name: NonelessLobby

commands:
  setlobby:
     description: Setze die lobby
  spawn:
     description: Gehe zum Spawn
  addFriend:
     description: Adde freunde!!!
  vote:
     description: Bekomme den Vote Link