#!/bin/bash

# NonelessLobby Test Server Setup Script
# This script automates the setup of a Minecraft test server with the NonelessLobby plugin

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
SERVER_DIR="minecraft-test-server"
PAPER_VERSION="1.20.4"
PAPER_BUILD="497"
MEMORY_MIN="2G"
MEMORY_MAX="2G"

echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   NonelessLobby Test Server Setup         ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""

# Check for Java
echo -e "${YELLOW}[1/7] Checking Java installation...${NC}"
if ! command -v java &> /dev/null; then
    echo -e "${RED}✗ Java is not installed. Please install Java 17 or higher.${NC}"
    exit 1
fi

JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
if [ "$JAVA_VERSION" -lt 17 ]; then
    echo -e "${RED}✗ Java 17 or higher is required. Found: Java $JAVA_VERSION${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Java $JAVA_VERSION detected${NC}"

# Check for Maven
echo -e "${YELLOW}[2/7] Checking Maven installation...${NC}"
if ! command -v mvn &> /dev/null; then
    echo -e "${RED}✗ Maven is not installed. Please install Maven 3.6 or higher.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Maven detected${NC}"

# Compile plugin
echo -e "${YELLOW}[3/7] Compiling NonelessLobby plugin...${NC}"
if [ -f "pom.xml" ]; then
    mvn clean package -q || {
        echo -e "${RED}✗ Build failed. Check the output above for errors.${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Plugin compiled successfully${NC}"
else
    echo -e "${RED}✗ pom.xml not found. Please run this script from the project root.${NC}"
    exit 1
fi

# Create server directory
echo -e "${YELLOW}[4/7] Setting up server directory...${NC}"
mkdir -p "$SERVER_DIR"
cd "$SERVER_DIR"

# Download Paper server
echo -e "${YELLOW}[5/7] Downloading Paper server (${PAPER_VERSION} Build ${PAPER_BUILD})...${NC}"
if [ ! -f "server.jar" ]; then
    PAPER_URL="https://api.papermc.io/v2/projects/paper/versions/${PAPER_VERSION}/builds/${PAPER_BUILD}/downloads/paper-${PAPER_VERSION}-${PAPER_BUILD}.jar"
    
    if command -v wget &> /dev/null; then
        wget -q --show-progress "$PAPER_URL" -O server.jar || {
            echo -e "${RED}✗ Failed to download Paper server${NC}"
            echo -e "${YELLOW}  Please download manually from: https://papermc.io/downloads${NC}"
            echo -e "${YELLOW}  Save as: $SERVER_DIR/server.jar${NC}"
            exit 1
        }
    elif command -v curl &> /dev/null; then
        curl -L --progress-bar "$PAPER_URL" -o server.jar || {
            echo -e "${RED}✗ Failed to download Paper server${NC}"
            echo -e "${YELLOW}  Please download manually from: https://papermc.io/downloads${NC}"
            echo -e "${YELLOW}  Save as: $SERVER_DIR/server.jar${NC}"
            exit 1
        }
    else
        echo -e "${RED}✗ Neither wget nor curl found. Cannot download server.${NC}"
        echo -e "${YELLOW}  Please install wget or curl, or download manually.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Paper server downloaded${NC}"
else
    echo -e "${GREEN}✓ Server JAR already exists${NC}"
fi

# Accept EULA
echo -e "${YELLOW}[6/7] Configuring server...${NC}"
echo "eula=true" > eula.txt
echo -e "${GREEN}✓ EULA accepted${NC}"

# Create server.properties
cat > server.properties << EOF
# Minecraft Server Configuration
# Generated by NonelessLobby setup script

# Basic Settings
online-mode=false
server-port=25565
max-players=20
view-distance=8
simulation-distance=8

# World Settings
level-name=world
level-type=minecraft\:flat
gamemode=adventure
difficulty=peaceful
hardcore=false
pvp=false
spawn-protection=0
spawn-animals=false
spawn-monsters=false
spawn-npcs=true

# Performance
max-tick-time=60000
max-world-size=29999984

# Misc
motd=§aNonelessLobby Test Server
enable-command-block=true
allow-flight=true
EOF
echo -e "${GREEN}✓ server.properties configured${NC}"

# Create plugins directory
mkdir -p plugins

# Copy plugin
echo -e "${YELLOW}[7/7] Installing NonelessLobby plugin...${NC}"
cp ../target/NonelessLobby-3.1.jar plugins/
echo -e "${GREEN}✓ Plugin installed${NC}"

# Create basic plugin config
mkdir -p plugins/NonelessLobby
cat > plugins/NonelessLobby/config.yml << EOF
# NonelessLobby Configuration
# Auto-generated configuration file

# MySQL Database Configuration (Optional)
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: nonelesslobby
  username: lobby
  password: change_me

# Lobby Settings
lobby:
  spawn-on-join: true
  protect-lobby-world: true
  disable-damage: true
  disable-hunger: true
  disable-item-drop: true
  disable-item-pickup: true

# Scoreboard Settings
scoreboard:
  enabled: true
  update-interval: 20

# NPC Settings (requires Citizens plugin)
npcs:
  enabled: false
  auto-spawn: true

# Friend System
friends:
  enabled: true
  max-friends: 50

# Points System
points:
  enabled: false
  starting-points: 0
EOF

# Create start script
cat > start.sh << 'EOF'
#!/bin/bash
java -Xms2G -Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar nogui
EOF

chmod +x start.sh

cat > start-simple.sh << 'EOF'
#!/bin/bash
java -Xms2G -Xmx2G -jar server.jar nogui
EOF

chmod +x start-simple.sh

# Return to original directory
cd ..

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Setup Complete! 🎉                ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. cd $SERVER_DIR"
echo -e "  2. ./start.sh (optimized) or ./start-simple.sh (basic)"
echo ""
echo -e "${YELLOW}Test the plugin with these commands:${NC}"
echo -e "  /lobby - Teleport to lobby spawn"
echo -e "  /help - View all available commands"
echo -e "  /serverinfo - View server information"
echo -e "  /settings - Open player settings"
echo ""
echo -e "${YELLOW}Admin commands (need OP):${NC}"
echo -e "  /setlobby - Set the lobby spawn point"
echo -e "  /punkteadmin - Manage points system"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo -e "  Server: $SERVER_DIR/server.properties"
echo -e "  Plugin: $SERVER_DIR/plugins/NonelessLobby/config.yml"
echo ""
echo -e "${GREEN}Happy testing! 🚀${NC}"
